export function getElements(root = document) {
  return {
    documentList: root.querySelector("#documentList"),
    outlineList: root.querySelector("#outlineList"),
    folderInlinePanel: root.querySelector("#folderInlinePanel"),
    folderNameInput: root.querySelector("#folderNameInput"),
    pageCanvas: root.querySelector("#pageCanvas"),
    editor: root.querySelector("#editor"),
    editorContextMenu: root.querySelector("#editorContextMenu"),
    commandPalette: root.querySelector("#commandPalette"),
    commandInput: root.querySelector("#commandInput"),
    commandResults: root.querySelector("#commandResults"),
    docTitle: root.querySelector("#docTitle"),
    workspaceMenuButton: root.querySelector("#workspaceMenuButton"),
    workspaceMenu: root.querySelector("#workspaceMenu"),
    themeToggleButton: root.querySelector("#themeToggleButton"),
    focusModeButton: root.querySelector("#focusModeButton"),
    openCommandButton: root.querySelector("#openCommandButton"),
    closeCommandButton: root.querySelector("#closeCommandButton"),
    projectMode: root.querySelector("#projectMode"),
    workingTitleInput: root.querySelector("#workingTitleInput"),
    researcherNameInput: root.querySelector("#researcherNameInput"),
    programmeFieldInput: root.querySelector("#programmeFieldInput"),
    supervisorsInput: root.querySelector("#supervisorsInput"),
    projectWorkStatusInput: root.querySelector("#projectWorkStatusInput"),
    targetVenueInput: root.querySelector("#targetVenueInput"),
    deadlineInput: root.querySelector("#deadlineInput"),
    keywordsInput: root.querySelector("#keywordsInput"),
    docStatus: root.querySelector("#docStatus"),
    citationStyleSelect: root.querySelector("#citationStyleSelect"),
    blockStyleSelect: root.querySelector("#blockStyleSelect"),
    fontFamilySelect: root.querySelector("#fontFamilySelect"),
    fontSizeSelect: root.querySelector("#fontSizeSelect"),
    lineHeightSelect: root.querySelector("#lineHeightSelect"),
    textAlignSelect: root.querySelector("#textAlignSelect"),
    textToolsButton: root.querySelector("#textToolsButton"),
    textToolsMenu: root.querySelector("#textToolsMenu"),
    zoomLevelLabel: root.querySelector("#zoomLevelLabel"),
    wordCount: root.querySelector("#wordCount"),
    charCount: root.querySelector("#charCount"),
    citationCount: root.querySelector("#citationCount"),
    topicLabel: root.querySelector("#topicLabel"),
    referenceTopic: root.querySelector("#referenceTopic"),
    focusOptions: root.querySelector("#focusOptions"),
    referenceSearch: root.querySelector("#referenceSearch"),
    referenceList: root.querySelector("#referenceList"),
    sourceCheckList: root.querySelector("#sourceCheckList"),
    sourceCheckStatus: root.querySelector("#sourceCheckStatus"),
    readingList: root.querySelector("#readingList"),
    selectionPreview: root.querySelector("#selectionPreview"),
    selectionCitationList: root.querySelector("#selectionCitationList"),
    zoteroLibraryType: root.querySelector("#zoteroLibraryType"),
    zoteroLibraryId: root.querySelector("#zoteroLibraryId"),
    zoteroApiKey: root.querySelector("#zoteroApiKey"),
    zoteroSearchInput: root.querySelector("#zoteroSearchInput"),
    zoteroStatus: root.querySelector("#zoteroStatus"),
    zoteroResults: root.querySelector("#zoteroResults"),
    researchQuestionInput: root.querySelector("#researchQuestionInput"),
    subQuestionsInput: root.querySelector("#subQuestionsInput"),
    methodologyInput: root.querySelector("#methodologyInput"),
    contributionInput: root.querySelector("#contributionInput"),
    meetingNotesInput: root.querySelector("#meetingNotesInput"),
    supervisorQuestionsInput: root.querySelector("#supervisorQuestionsInput"),
    revisionTasksInput: root.querySelector("#revisionTasksInput"),
    nextDeadlineInput: root.querySelector("#nextDeadlineInput"),
    supervisorCommentsInput: root.querySelector("#supervisorCommentsInput"),
    exportSupervisorCopyButton: root.querySelector("#exportSupervisorCopyButton"),
    literatureMatrix: root.querySelector("#literatureMatrix"),
    checkList: root.querySelector("#checkList"),
    runChecksButton: root.querySelector("#runChecksButton"),
    syncState: root.querySelector("#syncState"),
    githubInlinePanel: root.querySelector("#githubInlinePanel"),
    githubButton: root.querySelector("#githubButton"),
    githubRepoInput: root.querySelector("#githubRepoInput"),
    githubBranchInput: root.querySelector("#githubBranchInput"),
    githubTokenInput: root.querySelector("#githubTokenInput"),
    githubActionsButton: root.querySelector("#githubActionsButton"),
    githubActionsMenu: root.querySelector("#githubActionsMenu"),
    githubModeBadge: root.querySelector("#githubModeBadge"),
    githubDetail: root.querySelector("#githubDetail"),
    githubSyncMessage: root.querySelector("#githubSyncMessage"),
    rewriteModeSelect: root.querySelector("#rewriteModeSelect"),
    runRewriteButton: root.querySelector("#runRewriteButton"),
    rewriteOutput: root.querySelector("#rewriteOutput"),
    replaceSelectionButton: root.querySelector("#replaceSelectionButton"),
    backupMessage: root.querySelector("#backupMessage"),
    tabs: Array.from(root.querySelectorAll(".tab")),
    panels: Array.from(root.querySelectorAll(".panel")),
    exportProjectButton: root.querySelector("#exportProjectButton"),
    importProjectButton: root.querySelector("#importProjectButton"),
    clearLocalDataButton: root.querySelector("#clearLocalDataButton"),
    clearSessionTokensButton: root.querySelector("#clearSessionTokensButton"),
    importFileInput: root.querySelector("#importFileInput"),
    updateBanner: root.querySelector("#updateBanner"),
    updateReloadButton: root.querySelector("#updateReloadButton"),
    updateDismissButton: root.querySelector("#updateDismissButton"),
  };
}

export const projectFieldBindings = [
  ["projectMode", "mode", "dissertation-chapter"],
  ["workingTitleInput", "workingTitle", ""],
  ["researcherNameInput", "researcherName", ""],
  ["programmeFieldInput", "programmeField", ""],
  ["supervisorsInput", "supervisors", ""],
  ["projectWorkStatusInput", "workStatus", "Planning"],
  ["targetVenueInput", "targetVenue", ""],
  ["deadlineInput", "deadline", ""],
  ["keywordsInput", "keywords", ""],
  ["researchQuestionInput", "researchQuestion", ""],
  ["subQuestionsInput", "subQuestions", ""],
  ["methodologyInput", "methodology", ""],
  ["contributionInput", "contribution", ""],
  ["meetingNotesInput", "meetingNotes", ""],
  ["supervisorQuestionsInput", "supervisorQuestions", ""],
  ["revisionTasksInput", "revisionTasks", ""],
  ["nextDeadlineInput", "nextDeadline", ""],
  ["supervisorCommentsInput", "supervisorComments", ""],
];
